---
version: "3"

networks:
  influx:

services:
  influxdb:
    container_name: influx
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - ./mnt/data:/var/lib/influxdb2:rw
      - ./mnt/config:/root/influxdb:rw

    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${TOKEN}
    ports:
      - 8086:8086
    networks:
      - influx

  influxclient:
    container_name: influxclient
    depends_on:
      - influxdb
    build:
      context: .
    volumes:
      - .:/app
    environment:
      - INFLUXDB_ADDR=http://influx:8086
      - INFLUXDB_TOKEN=${TOKEN}
      - INFLUXDB_ORG=${ORG}
      - INFLUXDB_BUCKET=${BUCKET}
    networks:
      - influx